os: linux

dist: focal

language: go

go:
  - 1.17.x

services:
  - rabbitmq

addons:
  apt:
    packages:
      - rabbitmq-server

branches:
  only:
    - master

env:
  - BROKER_URI=amqp://guest:guest@127.0.0.1/

script:
  - make build
  - make test

notifications:
  email:
    - bifer@alea-soluciones.com
