language: go
go:
  - 1.4
  - 1.5
  - tip

before_install:
  - go get -u github.com/golang/lint/golint

install:
  - make deps
  - make build

services:
  - rabbitmq

script:
  - make test
  - go vet
  - golint

