language: go
go:
  - 1.10.x
  - 1.11.x
  - master

sudo: false

env:
  - BROKER_URI=amqp://guest:guest@localhost/

services:
  - rabbitmq

script:
  - make travis

notifications:
  email:
  - bifer@alea-soluciones.com