---
- hosts: felix:felixlite
  gather_facts: no

  vars_files:
    - ~/.felix/vars.yml

  tasks:
    - name: Include vars for environment
      include_vars: ~/.felix/vars_{{ inv_environment | default('production') }}.yml

    - name: Check that variables are defined
      assert:
        that:
          - component is defined
          - gitrevision is defined

    - import_role:
        name: bifer_docker_compose_component
      vars:
        bifer_docker_compose_component_path: "{{ docker_compose_etc }}/{{ component }}"
        bifer_docker_compose_component_compose_template: docker-compose.yml.j2
        bifer_docker_compose_component_gitrevision: "{{ gitrevision }}"
