---
- hosts: "felix"

  vars_files:
    - ~/.felix/vars.yml

  tasks:
    - name: setup private docker credentials
      copy:
        src=~/.felix/dockercfg
        dest=/root/.dockercfg

    - name: create /usr/local/bin
      file:
        path={{ item }}
        state=directory
        owner=root
        recurse=yes
      with_items:
        - /usr/local
        - /usr/local/bin

    - name: install docker-compose
      get_url:
        url=https://github.com/docker/compose/releases/download/1.4.0/docker-compose-linux-x86_64
        dest=/usr/local/bin/docker-compose
        force=yes

    - name: make executable docker-compose
      file:
        path=/usr/local/bin/docker-compose
        mode="u=rx,g=rx,o=rx"

    - name: create docker-compose dirs
      file:
        path={{ item }}
        state=directory
        recurse=yes
      with_items:
        - "{{ docker_compose_etc }}"
        - "{{ docker_compose_data }}"
