name: ci

on:
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      BROKER_URI: amqp://guest:guest@localhost:5666/

    services:
      rabbitmq:
        image: rabbitmq:3.7.4-management
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        ports:
          - 15666:15672
          - 5666:5672

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.17

      - name: Build
        run: make build

      - name: Test
        run: make test
